### PR TITLE
Update ToolList.md

### PR DESCRIPTION
**Pull request by RSoulatIOHK**
Added tools from Rudy Mutela that look interesting.

### CODE REVIEW

**Comment by RSoulatIOHK** [comment]
> Please review @RSoulatIOHK https://github.com/mlabs-haskell/plutus-simple-model https://github.com/mlabs-haskell/plutip https://github.com/tweag/cooked-validators
> 
> PSM was recommended as simplest way to have a unit test

Cooked should already be in it (I'll sort the tools by name tomorrow). I've added PSM and Plutip. Thanks :)

**Comment by aleeusgr** [comment]
https://github.com/tweag/cooked-smart-contracts

**Comment by aleeusgr** [comment]
https://github.com/mlabs-haskell/hedgehog-plutus-simple

https://github.com/mlabs-haskell/apropos

**Comment by RSoulatIOHK** [comment]
Sorry for not having reviewed your comments in the past weeks. I've been focused on the CIP draft. I'll do that today @aleeusgr

**Review by mmontin — APPROVED** [review]

**Pull request merged**
